export const newsLatest=[
{source:'Sneaker News',date:'2026-09-01',title:'The Joker Gets His Own Nike Air Max 95 Big Bubble',summary:'Nike follows its Batman-inspired Air Max 95 with a Joker-coded Big Bubble colorway featuring Canyon Purple, slimy green accents, a dark grey gradient, and jewel Swooshes.',image:'',url:'https://sneakernews.com/2026/08/31/nike-air-max-95-big-bubble-joker-iq0229-002/'},
{source:'Nice Kicks',date:'2026-08-31',title:'Victor Victor x Nike Air Force 1 Low “Black/White” Releases September 12',summary:'Victor Victor’s black-and-white Air Force 1 Low is scheduled to release September 12 through select retailers for $150, carrying style code IV3238-001.',image:'https://www.nicekicks.com/files/2026/08/HJHJGRZWAAABsfV-1-e1788222362903.jpg',url:'https://www.nicekicks.com/victor-victor-nike-air-force-1-low-black-white-iv3238-001/'},
{source:'Sneaker News',date:'2026-08-31',title:'Victor Victor x Nike Air Force 1 Low “University Red” Limited To 646 Pairs',summary:'Steven Victor confirmed the University Red Victor Victor Air Force 1 Low for September 12, with production limited to just 646 pairs.',image:'',url:'https://sneakernews.com/tag/nike-air-force-1/'},
{source:'Sneaker News',date:'2026-08-31',title:'Travis Scott And Nike Unveil Cactus Court Collection For US Open',summary:'Nike and Travis Scott officially unveiled the Cactus Court capsule with Air Force 1 Low and Zoom Vapor 12 footwear. The full collection launches September 4.',image:'',url:'https://sneakernews.com/2026/08/31/travis-scott-x-nike-air-force-1-low-releasing-today-at-47-chrystie/'},
{source:'Sneaker News',date:'2026-08-31',title:'APB x Air Jordan 11 Low Releases September 18',summary:'New details have surfaced for the APB Air Jordan 11 Low collaboration, scheduled for September 18 at $200.',image:'',url:'https://sneakernews.com/2026/08/31/apb-air-jordan-11-low-iu8266-400-release-date/'},
{source:'Sneaker News',date:'2026-08-31',title:'Caitlin Clark Reveals Nike Caitlin 1 Team USA PEs',summary:'Caitlin Clark unveiled two Team USA player editions ahead of the FIBA World Cup. The retail Caitlin 1 launches October 1 at $140.',image:'',url:'https://sneakernews.com/2026/08/31/nike-caitlin-1-fiba-world-cup-pe/'},
{source:'Sneaker News',date:'2026-08-31',title:'Yuto Horigome Nike SB Air Force 1 Laser Surfaces',summary:'A laser-etched Yuto Horigome Nike SB Air Force 1 has surfaced and is expected to arrive in late 2026 or early 2027.',image:'',url:'https://sneakernews.com/2026/08/31/yuto-horigome-nike-sb-air-force-1-white-red-iu3766-100/'},
{source:'Sneaker News',date:'2026-08-30',title:'adidas Harden Vol. 10 Purple Gradient',summary:'adidas extends James Harden’s tenth signature model with a new purple-gradient colorway.',image:'',url:'https://sneakernews.com/2026/08/30/adidas-harden-vol-10-purple-gradient-la5918/'}
];
