export const newsAuto=[
{source:'Sneaker News',date:'2026-09-04',title:'Nike Ja 4 “Dark Mode” Launches September 4',summary:'Ja Morant’s Nike Ja 4 arrives in the black, Cobalt Bliss and Metallic Silver “Dark Mode” colorway. The performance basketball shoe releases September 4 through select retailers, with a wider Nike launch September 8, for $130.',image:'',url:'https://sneakernews.com/2026/06/22/nike-ja-4-dark-mode-black-metallic-silver-cobalt-bliss-im4135-001/'},
{source:'Sneaker News',date:'2026-09-04',title:'Nike Twelve Time Debuts With Three $90 Ja Morant Colorways',summary:'Nike expands Ja Morant’s signature line with the budget-minded Twelve Time. The Dark Woods, Nightmare and Solar launch colorways release September 4 through Nike and select retailers for $90.',image:'',url:'https://sneakernews.com/2026/07/23/ja-morant-nike-twelve-time-release-date/'},
{source:'Sneaker News',date:'2026-09-03',title:'COMME des GARÇONS Announces Air Jordan 11 Collaboration',summary:'COMME des GARÇONS and Jordan Brand confirm black and white Air Jordan 11 colorways releasing September 5 exclusively through Dover Street Market and COMME des GARÇONS stores for $358.',image:'',url:'https://sneakernews.com/2026/09/03/comme-des-garcons-air-jordan-11-release-date/'},
{source:'Sneaker News',date:'2026-09-03',title:'Jigsaw And Michael Myers Star In The Latest Crocs “Horror Pack” For Halloween',summary:'Crocs continues its Halloween Horror Pack with new Classic Clogs inspired by Jigsaw and Michael Myers, following previous horror-themed collaborations with Freddy Krueger, Jason Voorhees, Pennywise and Chucky.',image:'',url:'https://sneakernews.com/2026/09/03/halloween-crocs-classic-clog-jigsaw-michael-myers/'},
{source:'Sneaker News',date:'2026-09-03',title:'Where To Buy The Nike Air Diamond Turf 2 “49ers”',summary:'The Nike Air Diamond Turf 2 returns in its San Francisco 49ers-inspired colorway on September 4, 2026, with a full-family-size release.',image:'',url:'https://sneakernews.com/2026/09/03/nike-air-diamond-turf-2-49ers-store-list/'},
{source:'Sneaker News',date:'2026-09-03',title:'Nike Zoom GT Cut 4 “Sunset” Releases September 16',summary:'Nike dresses the Zoom GT Cut 4 in a yellow-to-orange-to-black Sunset gradient. The basketball model releases September 16 for $200.',image:'',url:'https://sneakernews.com/2026/09/03/nike-zoom-gt-cut-4-sunset-hv9922-900/'},
{source:'Sneaker News',date:'2026-09-03',title:'adidas And Damian Lillard “Meet The Moment” On The Dame X',summary:'adidas and Damian Lillard continue the Dame X line with the new “Meet The Moment” edition as Lillard returns to Portland.',image:'',url:'https://sneakernews.com/2026/09/03/adidas-dame-x-meet-the-moment-kj4404/'}
];
