export const releases=[
{date:'Aug 31',brand:'Reebok',name:'Angel Reese 1 “Aqua”',price:130,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
{date:'Aug 31',brand:'Reebok',name:'Angel Reese 1 “Metal Green”',price:130,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
{date:'Sep 01',brand:'adidas',name:'adidas Originals by JENNIE Superstar SQ Ballet',price:130,image:'',url:'https://www.adidas.com/us/adidas-jennie-superstar-sq-ballet-shoes/LB3786.html',source:'adidas'},
{date:'Sep 01',brand:'Nike',name:'Kobe Bryant × Nike Air Force 1 Low “Armory Blue”',price:125,image:'https://www.nicekicks.com/files/2026/07/ib0018-103-5-1200x1200.jpg',url:'https://www.nicekicks.com/kobe-bryant-nike-air-force-1-low-armory-blue-ib0018-103/',source:'Nice Kicks'},
{date:'Sep 01',brand:'Nike',name:'Zoom Hyperflight “Varsity Red”',price:170,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
{date:'Sep 01',brand:'Nike',name:'Kobe 3 Low Protro “Electric Green”',price:190,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
{date:'Sep 01',brand:'Nike',name:'Kobe 3 Low Protro “Pure Platinum”',price:190,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
{date:'Sep 01',brand:'Nike',name:'NFL × Nike Air Max 90 Rivalries “Texans”',price:140,image:'https://www.nicekicks.com/files/2026/08/iw1135-100-5-1-1200x1200.jpg',url:'https://www.nicekicks.com/nfl-x-nike-air-max-90-rivalries-texans-iw1135-100/',source:'Nice Kicks'},
{date:'Sep 02',brand:'Jordan',name:'Air Jordan 1 High OG WMNS “Nails & Grails”',price:185,image:'https://static.nike.com/a/images/t_default/FD2596-601.png',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
{date:'Sep 04',brand:'Nike',name:'Kobe Bryant × Nike Dunk Low Protro “FC Barcelona”',price:135,image:'',url:'https://www.nicekicks.com/nike-kobe-release-dates/',source:'Nice Kicks'},
{date:'Sep 04',brand:'Nike',name:'Nike Kobe 3 Low Protro × FC Barcelona',price:190,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
{date:'Sep 05',brand:'Jordan',name:'Air Jordan 4 “Tour Yellow”',price:220,image:'',url:'https://www.nicekicks.com/air-jordan-4-tour-yellow-io2463-102-drop/',source:'Nice Kicks'},
{date:'Sep 05',brand:'Jordan',name:'Comme des Garçons × Air Jordan 11 “Triple Black”',price:250,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
{date:'Sep 05',brand:'Jordan',name:'Comme des Garçons × Air Jordan 11 “Triple White”',price:250,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
{date:'Sep 08',brand:'Nike',name:'Air Max 95 Big Bubble OG “Reverse Greedy”',price:200,image:'https://www.nicekicks.com/files/2026/08/im2211-001-5-1-1200x1200.jpg',url:'https://www.nicekicks.com/nike-air-max-95-big-bubble-og-reverse-greedy-im2211-001/',source:'Nice Kicks'},
{date:'Sep 09',brand:'Jordan',name:'Air Jordan 7 “Tennis Day”',price:215,image:'https://static.nike.com/a/images/w_320,q_auto,f_auto/9aa14f9e-8633-4899-ab4e-0205c6befaa4/air-jordan-7-tennis-day-phantom-and-lime-blast-iv6508-030-release-date.jpg',url:'https://www.nike.com/launch/t/air-jordan-7-phantom-and-lime-blast',source:'Nike SNKRS'},
{date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 SP “Burnt Red”',price:255,image:'',url:'https://www.nicekicks.com/mowalola-air-jordan-14-sp-burnt-red-iq5708-001/',source:'Nice Kicks'},
{date:'Sep 19',brand:'Jordan',name:'Air Jordan 9 OG “Space Jam”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-9-og-space-jam-hv4794-106-drop/',source:'Nice Kicks'},
{date:'Sep 19',brand:'Nike',name:'Nike Kobe 8 Protro “Mambacurial”',price:200,image:'',url:'https://www.nicekicks.com/nike-kobe-release-dates/',source:'Nice Kicks'},
{date:'Dec 12',brand:'Jordan',name:'Air Jordan 11 “Space Jam”',price:235,image:'',url:'https://www.nicekicks.com/air-jordan-11-space-jam-ct8012-900-drop/',source:'Nice Kicks'}
];
