export const dailyReleaseUpdates=[
  {date:'Sep 12',brand:'Jordan',name:'Air Jordan 12 “Bucks”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “University Red”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Yellow Zest”',price:150,image:'',url:'https://www.nicekicks.com/victor-victor-nike-air-force-1-low-yellow-zest-iv3238-700/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Court Purple”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Black/White”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Wagyu × Nike Air Max 90 “Black”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'adidas',name:'Larry June × adidas Adistar Control 5 “Watermelon Smoothie”',price:160,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas / Nice Kicks'},
  {date:'Sep 12',brand:'ANTA',name:'ANTA KAI 3 “Alchemist”',price:135,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 15',brand:'Nike',name:'Yuto Horigome × Nike SB Air Force 1 Low “Iron Grey”',price:125,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Mirage WMNS “Light Crimson”',price:170,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Shadow WMNS “Light Crimson”',price:145,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 15',brand:'adidas',name:'adidas Samba OG Shoes',price:120,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 16',brand:'Jordan',name:'Air Jordan 6 Low WMNS “Metamorphosis”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Nike',name:'Nike Air Foamposite One “Green Camo”',price:200,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Nike',name:'Nike LeBron 23 PE “Laser”',price:210,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'APB × Air Jordan 11 Low “Binary Blue”',price:200,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 SP “Burnt Red”',price:255,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 Mule SP “Metallic Silver”',price:180,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'adidas',name:'adidas Superstar II Shoes',price:110,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 18',brand:'adidas',name:'adidas Anthony Edwards 3 “Cold Blooded”',price:130,image:'',url:'https://www.nicekicks.com/adidas-anthony-edwards-3-cold-blooded-kh8537-2026/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'adidas',name:'Anthony Edwards × adidas Superstar II “Bliss Blue”',price:110,image:'',url:'https://www.nicekicks.com/anthony-edwards-adidas-superstar-ii-bliss-blue-la7828/',source:'Nice Kicks'},
  {date:'Sep 19',brand:'Jordan',name:'Air Jordan 9 OG “Space Jam”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 19',brand:'Nike',name:'Nike Kobe 8 Protro “Mambacurial”',price:200,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 21',brand:'Nike',name:'PSG × Nike KD 6 “Metallic Silver”',price:135,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Pikachu White”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Samba OG “Mewtwo”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Charmander”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Jordan',name:'Air Jordan 5 WMNS “Sunset”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Reebok',name:'Billionaire Boys Club × Reebok Club C 85 “Grey”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Gomu Gomu no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-gomu-gomu-no-mi-ir0968-500/',source:'Nike / Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Ope Ope no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-ope-ope-no-mi-iw1282-600/',source:'Nike / Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Mera Mera no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-mera-mera-no-mi-iw1283-800/',source:'Nike / Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 4014 “Ferrari”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 1 Low OG “Last Dance At The Garden”',price:155,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'adidas',name:'Bad Bunny × adidas BadBo 1.1 “Chalk White”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Oct 06',brand:'adidas',name:'adidas Samba Climbing Shoes',price:120,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'}
];