export const dailyReleaseUpdates=[
  {date:'Sep 04',brand:'Nike',name:'Nike Ja Twelve Time “Atomic Pink”',price:90,image:'',url:'https://www.nicekicks.com/nike-ja-twelve-time-atomic-pink-im4164-600/',source:'Nice Kicks'},
  {date:'Sep 04',brand:'Nike',name:'Nike Air Diamond Turf II “49ers”',price:170,image:'',url:'https://www.nicekicks.com/nike-air-diamond-turf-ii-49ers-ii7080-001/',source:'Nice Kicks'},
  {date:'Sep 04',brand:'adidas',name:'adidas Harden Vol. 10 “Ray Blue”',price:160,image:'',url:'https://www.nicekicks.com/adidas-harden-vol-10-ray-blue-ki1610/',source:'Nice Kicks'},
  {date:'Sep 08',brand:'Nike',name:'Air Max 95 Big Bubble OG “Reverse Greedy”',price:200,image:'https://www.nicekicks.com/files/2026/08/im2211-001-5-1-1200x1200.jpg',url:'https://www.nicekicks.com/nike-air-max-95-big-bubble-og-reverse-greedy-im2211-001/',source:'Nice Kicks'},
  {date:'Sep 08',brand:'Nike',name:'Nike KD 19 “Candy Paint Green”',price:155,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 08',brand:'Nike',name:'Nike G.T. Future “Varsity Red”',price:200,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 09',brand:'Nike',name:'Terror Squad × Nike Air Force 1 Low QS “University Red”',price:150,image:'',url:'https://www.nicekicks.com/terror-squad-air-force-1-low-qs-university-red-ii4391-100-drop/',source:'Nice Kicks'},
  {date:'Sep 09',brand:'Jordan',name:'Air Jordan 7 “Tennis Day”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 09',brand:'adidas',name:'Tyrrell Winston × adidas Climacool 4D “Collegiate Red”',price:180,image:'',url:'https://news.adidas.com/sportswear/adidas-and-tyrrell-winston-unveil-new-collection-celebrating-resilience--dedication-and-the-athlete-/s/171be58f-96fa-4fe4-8ac1-78bd9445e68e',source:'adidas / Nice Kicks'},
  {date:'Sep 09',brand:'Reebok',name:'Reebok DMX 3000 Series “Vector Blue”',price:130,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 10',brand:'Nike',name:'Chevrolet × Nike Book 2 “Pretty Penny”',price:155,image:'',url:'https://www.nicekicks.com/chevrolet-nike-book-2-pretty-penny-io9841-900/',source:'Nice Kicks'},
  {date:'Sep 10',brand:'Nike',name:'Penny Hardaway × Nike Air Zoom Huarache 2K4 PE “Knicks”',price:200,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 10',brand:'Jordan',name:'Air Jordan 3 TD Football Cleats “Metallic Silver”',price:205,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 10',brand:'Vans',name:'Vans Old Skool 36 “Yatch Club”',price:125,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 10',brand:'adidas',name:'Simone Rocha × adidas SR Taekwondo Ballerina',price:250,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 10',brand:'adidas',name:'Simone Rocha × adidas SR Climacool',price:250,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 10',brand:'adidas',name:'Simone Rocha × adidas SR Japan Slip-on Shoes',price:220,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 12',brand:'Jordan',name:'Air Jordan 12 “Idols Become Rivals”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-12-idols-becomes-rivals-ct8013-103-drop/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “University Red”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Yellow Zest”',price:150,image:'',url:'https://www.nicekicks.com/victor-victor-nike-air-force-1-low-yellow-zest-iv3238-700/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Court Purple”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Black/White”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Wagyu × Nike Air Max 90 “Black”',price:150,image:'',url:'https://www.nicekicks.com/wagyu-x-nike-air-max-90-black-ir1979-010/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'adidas',name:'Larry June × adidas Adistar Control 5 “Semi Lucid Red”',price:160,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 15',brand:'Nike',name:'Yuto Horigome × Nike SB Air Force 1 Low “Iron Grey”',price:125,image:'',url:'https://www.nike.com/us/es/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Mirage WMNS “Light Crimson”',price:170,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Shadow WMNS “Light Crimson”',price:145,image:'',url:'https://www.nicekicks.com/nike-first-sight-shadow-wmns-light-crimson-hq2410-600/',source:'Nice Kicks'},
  {date:'Sep 16',brand:'Jordan',name:'Air Jordan 6 Low WMNS “Metamorphosis”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'JAIDE × Air Jordan 11 Low WMNS “Fiberglass”',price:200,image:'',url:'https://www.nicekicks.com/jaide-air-jordan-11-low-wmns-fiberglass-iw1882-300/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'APB × Air Jordan 11 Low “Binary Blue”',price:200,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 SP “Burnt Red”',price:255,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 Mule SP “Metallic Silver”',price:180,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
  {date:'Sep 19',brand:'Jordan',name:'Air Jordan 9 OG “Space Jam”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Handball Spezial “Mewtwo”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Megaride F50 “Rayquaza”',price:200,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Pikachu Yellow”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar Vintage “Charizard”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar II “Charmaleon”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Charmander”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Samba OG “Mewtwo”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas ZX 500 “Rayquaza”',price:100,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas ZX 8000 “Mewtwo”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Adistar Control 5 “Haunter”',price:130,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Adistar Control 3 “Gastly”',price:130,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Adistar XLG 2.0 “Gengar”',price:170,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Jordan',name:'Air Jordan 5 WMNS “Sunset”',price:205,image:'',url:'https://www.nicekicks.com/air-jordans/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Reebok',name:'Billionaire Boys Club × Reebok Club C 85 “Grey”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 4014 “Ferrari”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-4014-ferrari-ir2082-600/',source:'Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 1 Low OG “Last Dance At The Garden”',price:155,image:'',url:'https://www.nicekicks.com/air-jordan-1-low-og-last-dance-at-the-garden-ir0088-001/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'adidas',name:'Bad Bunny × adidas BadBo 1.1 “Chalk White”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'}
];
