export const dailyReleaseUpdates=[
  {date:'Sep 12',brand:'Jordan',name:'Air Jordan 12 “Idols Become Rivals”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-12-idols-becomes-rivals-ct8013-103-drop/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “University Red”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Yellow Zest”',price:150,image:'',url:'https://www.nicekicks.com/victor-victor-nike-air-force-1-low-yellow-zest-iv3238-700/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Court Purple”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Victor Victor × Nike Air Force 1 Low “Black/White”',price:150,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'Nike',name:'Wagyu × Nike Air Max 90 “Black”',price:150,image:'',url:'https://www.nicekicks.com/wagyu-x-nike-air-max-90-black-ir1979-010/',source:'Nice Kicks'},
  {date:'Sep 12',brand:'adidas',name:'Larry June × adidas Adistar Control 5 “Watermelon Smoothie”',price:160,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas / Nice Kicks'},
  {date:'Sep 12',brand:'ANTA',name:'ANTA KAI 3 “Alchemist”',price:135,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 15',brand:'Nike',name:'Yuto Horigome × Nike SB Air Force 1 Low “Iron Grey”',price:125,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Mirage WMNS “Light Crimson”',price:170,image:'',url:'https://www.nike.com/launch/upcoming',source:'Nike SNKRS'},
  {date:'Sep 15',brand:'Nike',name:'Nike First Sight Shadow WMNS “Light Crimson”',price:145,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 15',brand:'adidas',name:'adidas Samba OG Shoes',price:120,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 16',brand:'Jordan',name:'Air Jordan 6 Low WMNS “Metamorphosis”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 16',brand:'New Balance',name:'New Balance 1890A “Cowprint”',price:200,image:'',url:'https://www.nicekicks.com/new-balance-1890a-cowprint-u18906m2/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Nike',name:'Nike Air Foamposite One “Green Camo”',price:240,image:'',url:'https://www.nicekicks.com/nike-air-foamposite-one-green-camo-im5204-001/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Nike',name:'Nike LeBron 23 PE “Laser”',price:210,image:'',url:'https://www.nicekicks.com/nike-lebron-23-pe-laser-im5125-100/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'JAIDE × Air Jordan 11 Low WMNS “Fiberglass”',price:200,image:'',url:'https://www.nicekicks.com/jaide-air-jordan-11-low-wmns-fiberglass-iw1882-300/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'APB × Air Jordan 11 Low “Binary Blue”',price:200,image:'',url:'https://www.nicekicks.com/apb-air-jordan-11-low-binary-blue-iu8266-400/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 SP “Burnt Red”',price:255,image:'',url:'https://www.nicekicks.com/mowalola-air-jordan-14-sp-burnt-red-iq5708-001/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'Jordan',name:'MOWALOLA × Air Jordan 14 Mule SP “Metallic Silver”',price:180,image:'',url:'https://www.nicekicks.com/mowalola-air-jordan-14-mule-sp-metallic-silver-ir0908-001/',source:'Nice Kicks'},
  {date:'Sep 18',brand:'adidas',name:'adidas Superstar II Shoes',price:110,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'},
  {date:'Sep 18',brand:'adidas',name:'adidas Anthony Edwards 3 “Cold Blooded”',price:130,image:'',url:'https://www.nicekicks.com/adidas-anthony-edwards-3-cold-blooded-kh8537-2026/',source:'adidas / Nice Kicks'},
  {date:'Sep 18',brand:'adidas',name:'Anthony Edwards × adidas Superstar II “Bliss Blue”',price:110,image:'',url:'https://www.nicekicks.com/anthony-edwards-adidas-superstar-ii-bliss-blue-la7828/',source:'Nice Kicks'},
  {date:'Sep 19',brand:'Jordan',name:'Air Jordan 9 OG “Space Jam”',price:215,image:'',url:'https://www.nicekicks.com/air-jordan-9-og-space-jam-ix6179-100-drop/',source:'Nice Kicks'},
  {date:'Sep 19',brand:'Nike',name:'Nike Kobe 8 Protro “Mambacurial”',price:200,image:'',url:'https://www.nicekicks.com/nike-kobe-8-protro-mambacurial-io6253-500/',source:'Nice Kicks'},
  {date:'Sep 21',brand:'Nike',name:'PSG × Nike KD 6 “Metallic Silver”',price:135,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'Nike',name:'Nike G.T. Future “Varsity Red”',price:200,image:'',url:'https://www.nicekicks.com/nike-g-t-future-varsity-red-fz5590-603/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'Nike',name:'Nike Air Force 1 Low Cracked Leather “Black”',price:140,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Pikachu White”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Samba OG “Mewtwo”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar “Charmander”',price:110,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar II “Charmaleon”',price:110,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Superstar Vintage “Charizard”',price:110,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Pro Model “Pikachu”',price:180,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas ZX 500 “Rayquaza”',price:100,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas ZX 8000 “Mewtwo”',price:150,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Adistar Control 5 “Haunter”',price:130,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 22',brand:'adidas',name:'Pokémon × adidas Adistar Control 3 “Gastly”',price:130,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 23',brand:'Nike',name:'Nike G.T. Future EYBL Unseen Hours “Peach Jam”',price:210,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 24',brand:'Jordan',name:'Jordan Tatum 5 “Sunrise”',price:125,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 24',brand:'PUMA',name:'PUMA MB.06 “Shooting Star”',price:130,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 24',brand:'Converse',name:'Converse SHAI 001 Shroud “Spark”',price:140,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 24',brand:'Converse',name:'Converse SHAI 001 Shroud “Shock”',price:140,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Jordan',name:'Air Jordan 5 WMNS “Sunset”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-release-dates/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Reebok',name:'Billionaire Boys Club × Reebok Club C 85 “Grey”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'Nike Ja 4 “Deep Water”',price:130,image:'',url:'https://www.nicekicks.com/nike-ja-4-deep-water-im4135-401/',source:'Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Gomu Gomu no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-gomu-gomu-no-mi-ir0968-500/',source:'Nike / Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Ope Ope no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-ope-ope-no-mi-iw1282-600/',source:'Nike / Nice Kicks'},
  {date:'Sep 25',brand:'Nike',name:'One Piece × Nike Air Max Plus SP “Mera Mera no Mi”',price:210,image:'',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-mera-mera-no-mi-iw1283-800/',source:'Nike / Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 4014 “Ferrari”',price:205,image:'',url:'https://www.nicekicks.com/air-jordan-4014-ferrari-ir2082-600/',source:'Nice Kicks'},
  {date:'Sep 26',brand:'Jordan',name:'Air Jordan 1 Low OG “Last Dance At The Garden”',price:155,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Sep 26',brand:'Nike',name:'Nike Kobe 3 Protro “Black/White”',price:210,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Sep 29',brand:'Nike',name:'Nike Air Bakin SP “OG”',price:170,image:'',url:'https://www.nicekicks.com/nike-air-bakin-sp-og-iq5365-600/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'Nike',name:'Nike Caitlin 1 “Caitlin Blue”',price:140,image:'',url:'https://www.nicekicks.com/nike-caitlin-1-caitlin-blue-ih7423-400/',source:'Nike / Nice Kicks'},
  {date:'Oct 01',brand:'Nike',name:'Nike Caitlin 1 “Warning Code”',price:140,image:'',url:'https://www.nicekicks.com/nike-caitlin-1-warning-code-ih7423-700/',source:'Nike / Nice Kicks'},
  {date:'Oct 01',brand:'Jordan',name:'Air Jordan 1 Low OG “Howard”',price:165,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'Nike',name:'Nike Air Force 1 Low “Ghostface”',price:125,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'New Balance',name:'New Balance 983 “Shadow Blue”',price:160,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'Nike',name:'Nike Book 2 “Desert Night”',price:145,image:'',url:'https://www.nicekicks.com/sneaker-release-dates/',source:'Nice Kicks'},
  {date:'Oct 01',brand:'adidas',name:'Bad Bunny × adidas BadBo 1.1 “Chalk White”',price:120,image:'',url:'https://www.nicekicks.com/release-dates/sneaker-releases/',source:'Nice Kicks'},
  {date:'Oct 06',brand:'adidas',name:'adidas Samba Climbing Shoes',price:120,image:'',url:'https://www.adidas.com/us/release-dates',source:'adidas'}
];