const URL='https://mmazwydwswrkqgisotyt.supabase.co/rest/v1/shoe_products';
const KEY='sb_publishable_qsygJlwjwTVKrumOCyJC5A_Zptqj4xZ';
const KICKS_URL='https://api.kicks.dev/v3/stockx/products';
const BRANDS={1:'Nike',2:'Jordan',3:'Adidas',4:'Yeezy',5:'Balmain',6:'Christian Louboutin',7:'Louis Vuitton',8:'Gucci',9:'Versace',10:'Balenciaga'};
const KICKS_BRANDS=['Nike','Jordan','adidas','New Balance','ASICS','Puma','Reebok','Converse','Vans','Saucony','Salomon','Yeezy','Gucci','Louis Vuitton','Balenciaga','Christian Louboutin','Versace'];
const BRAND_TARGET=300;
const KICKS_PAGE_SIZE=100;
const KICKS_PAGES=Math.ceil(BRAND_TARGET/KICKS_PAGE_SIZE);
const BRAND_BATCH_SIZE=4;
const BRAND_LABELS={'adidas':'Adidas','asics':'ASICS','puma':'Puma','yeezy':'Yeezy'};
const BAD_IMAGE=/(ebayimg\.com|flightclub\.com|flightclub|\/TEMPLATE\/|placeholder|logo[-_.])/i;
const DARK_SHOE=/\b(black|onyx|triple black|black cat|anthracite|dark|noir|shadow)\b/i;
function cleanName(v=''){return v.replace(/\s*\|\s*(Flight Club|eBay).*$/i,'').replace(/\s+-\s+(Nike|Adidas|Air Jordan)\s+-\s+.*$/i,'').trim()||'Dicey Shoe'}
function goodImage(v=''){return /^https:\/\//i.test(v)&&!BAD_IMAGE.test(v)}
function keyName(v=''){return cleanName(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function prettyBrand(v=''){const k=String(v).trim();return BRAND_LABELS[k.toLowerCase()]||k||'Sneakers'}
function mapProduct(x){const usd=x.currency==='USD'&&x.retail_price!=null?Number(x.retail_price):null;const name=cleanName(x.name);return{slug:`db-${x.product_id}`,dbId:x.product_id,brand:BRANDS[x.brand_id]||'Dicey Shoes',name,model:x.model||'',price:usd,category:/GUCCI|LOUIS|BALENCIAGA|VERSACE|BALMAIN|LOUBOUTIN/i.test(BRANDS[x.brand_id]||'')?'Luxury':'Sneakers',gender:(x.gender||'Unisex').replace(/^UNISEX$/i,'Unisex').replace(/^MEN$/i,'Men').replace(/^WOMEN$/i,'Women'),image:x.image_url,status:'In Stock',imageMode:DARK_SHOE.test(name)?'dark':'normal',sizes:Array.isArray(x.available_sizes)&&x.available_sizes.length?x.available_sizes:['7','8','9','10','11','12'],description:x.description||'',source:'Dicey Inventory',referenceOnly:false}}
function mapKicks(x){const name=cleanName(x.title||x.name||'');const market=x.min_price!=null?Number(x.min_price):(x.avg_price!=null?Number(x.avg_price):null);const brand=prettyBrand(x.brand);return{slug:`kicks-${x.slug||x.id}`,kicksId:x.id||null,sku:x.sku||'',brand,name,model:x.model||'',price:market,marketPrice:market,category:/GUCCI|LOUIS VUITTON|BALENCIAGA|LOUBOUTIN|VERSACE/i.test(brand)?'Luxury':'Sneakers',gender:(x.gender||'Unisex').replace(/^men$/i,'Men').replace(/^women$/i,'Women').replace(/^unisex$/i,'Unisex'),image:x.image||'',status:'Market Reference',imageMode:DARK_SHOE.test(name)?'dark':'normal',sizes:['7','8','9','10','11','12'],description:x.description||'Market reference product powered by KicksDB.',source:'KicksDB',referenceOnly:true,market:x.market||'US',weeklyOrders:x.weekly_orders||0,rank:x.rank||null}}
async function getInventory(){const qs='?select=product_id,brand_id,name,model,gender,category,retail_price,currency,available_sizes,image_url,description,status&status=eq.PUBLISHED&order=product_id.asc&limit=1000';const r=await fetch(URL+qs,{headers:{apikey:KEY},next:{revalidate:3600}});if(!r.ok)throw new Error('catalog '+r.status);return r.json()}
async function getBrandPage(apiKey,brand,page){const qs=new URLSearchParams({page:String(page),limit:String(KICKS_PAGE_SIZE),filters:`brand = "${brand}" AND product_type = "sneakers"`});const r=await fetch(`${KICKS_URL}?${qs}`,{headers:{Authorization:`Bearer ${apiKey}`},next:{revalidate:21600}});if(!r.ok)throw new Error(`kicks ${brand} page ${page} ${r.status}`);const j=await r.json();return Array.isArray(j?.data)?j.data:[]}
async function getBrandShoes(apiKey,brand){const pages=[];for(let page=1;page<=KICKS_PAGES;page++){const rows=await getBrandPage(apiKey,brand,page);pages.push(...rows);if(rows.length<KICKS_PAGE_SIZE)break}return pages.slice(0,BRAND_TARGET)}
async function getKicks(){const apiKey=process.env.KICKS_API_KEY;if(!apiKey)return{rows:[],brandCounts:{},errors:[]};const rows=[],brandCounts={},errors=[];for(let i=0;i<KICKS_BRANDS.length;i+=BRAND_BATCH_SIZE){const batch=KICKS_BRANDS.slice(i,i+BRAND_BATCH_SIZE);const results=await Promise.all(batch.map(async brand=>{try{return{brand,items:await getBrandShoes(apiKey,brand)}}catch(e){return{brand,items:[],error:e.message}}}));for(const result of results){if(result.error)errors.push(result.error);brandCounts[prettyBrand(result.brand)]=result.items.length;rows.push(...result.items)}}return{rows,brandCounts,errors}}
export async function GET(){try{const rows=await getInventory();const inventory=rows.filter(x=>goodImage(x.image_url)).map(mapProduct);let kicksData={rows:[],brandCounts:{},errors:[]};try{kicksData=await getKicks()}catch(e){console.error('KicksDB enrichment unavailable',e.message)}const kicks=kicksData.rows.filter(x=>goodImage(x.image)).map(mapKicks);const names=new Set(inventory.map(x=>keyName(x.name)));const skus=new Set(inventory.map(x=>String(x.sku||'').toUpperCase()).filter(Boolean));const brandAdded={};const added=[];for(const p of kicks){const nk=keyName(p.name),sku=String(p.sku||'').toUpperCase();if(!nk||names.has(nk)||(sku&&skus.has(sku)))continue;names.add(nk);if(sku)skus.add(sku);brandAdded[p.brand]=(brandAdded[p.brand]||0)+1;added.push(p)}const products=[...inventory,...added];return Response.json({products,count:products.length,inventoryCount:inventory.length,kicksAdded:added.length,brandTarget:BRAND_TARGET,kicksBrands:KICKS_BRANDS.map(prettyBrand),kicksFetchedByBrand:kicksData.brandCounts,kicksAddedByBrand:brandAdded,kicksErrors:kicksData.errors,excluded:rows.length-inventory.length,kicksEnabled:Boolean(process.env.KICKS_API_KEY)},{headers:{'Cache-Control':'public, s-maxage=3600, stale-while-revalidate=21600'}})}catch(e){return Response.json({products:[],count:0,error:'catalog unavailable'},{status:503})}}
