const URL='https://mmazwydwswrkqgisotyt.supabase.co/rest/v1/shoe_products';
const KEY='sb_publishable_qsygJlwjwTVKrumOCyJC5A_Zptqj4xZ';
const BRANDS={1:'Nike',2:'Jordan',3:'Adidas',4:'Yeezy',5:'Balmain',6:'Christian Louboutin',7:'Louis Vuitton',8:'Gucci',9:'Versace',10:'Balenciaga'};
const BAD_IMAGE=/(ebayimg\.com|flightclub\.com|flightclub|\/TEMPLATE\/|placeholder|logo[-_.])/i;
const DARK_SHOE=/\b(black|onyx|triple black|black cat|anthracite|dark|noir|shadow)\b/i;
function cleanName(v=''){return v.replace(/\s*\|\s*(Flight Club|eBay).*$/i,'').replace(/\s+-\s+(Nike|Adidas|Air Jordan)\s+-\s+.*$/i,'').trim()||'Dicey Shoe'}
function goodImage(v=''){return /^https:\/\//i.test(v)&&!BAD_IMAGE.test(v)}
function mapProduct(x){const usd=x.currency==='USD'&&x.retail_price!=null?Number(x.retail_price):null;const name=cleanName(x.name);return{slug:`db-${x.product_id}`,dbId:x.product_id,brand:BRANDS[x.brand_id]||'Dicey Shoes',name,model:x.model||'',price:usd,category:/GUCCI|LOUIS|BALENCIAGA|VERSACE|BALMAIN|LOUBOUTIN/i.test(BRANDS[x.brand_id]||'')?'Luxury':'Sneakers',gender:(x.gender||'Unisex').replace(/^UNISEX$/i,'Unisex').replace(/^MEN$/i,'Men').replace(/^WOMEN$/i,'Women'),image:x.image_url,status:'In Stock',imageMode:DARK_SHOE.test(name)?'dark':'normal',sizes:Array.isArray(x.available_sizes)&&x.available_sizes.length?x.available_sizes:['7','8','9','10','11','12'],description:x.description||''}}
export async function GET(){try{const qs='?select=product_id,brand_id,name,model,gender,category,retail_price,currency,available_sizes,image_url,description,status&status=eq.PUBLISHED&order=product_id.asc&limit=1000';const r=await fetch(URL+qs,{headers:{apikey:KEY},next:{revalidate:3600}});if(!r.ok)throw new Error('catalog '+r.status);const rows=await r.json();const products=rows.filter(x=>goodImage(x.image_url)).map(mapProduct);return Response.json({products,count:products.length,excluded:rows.length-products.length},{headers:{'Cache-Control':'public, s-maxage=3600, stale-while-revalidate=86400'}})}catch(e){return Response.json({products:[],count:0,error:'catalog unavailable'},{status:503})}}
