function text(s=''){return s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&rsquo;/g,'’').replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/\s+/g,' ').trim()}
function tag(item,name){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?text(m[1]):''}
function image(item){let m=item.match(/<media:content[^>]+url=["']([^"']+)/i)||item.match(/<media:thumbnail[^>]+url=["']([^"']+)/i)||item.match(/<enclosure[^>]+url=["']([^"']+)/i)||item.match(/<img[^>]+src=["']([^"']+)/i);return m?m[1]:''}
function parse(xml,source){return (xml.match(/<item[\s\S]*?<\/item>/gi)||[]).slice(0,12).map(i=>({source,title:tag(i,'title'),url:tag(i,'link'),date:tag(i,'pubDate'),summary:tag(i,'description').slice(0,220),image:image(i)})).filter(x=>x.title&&x.url)}
const TRUSTED_ARTICLE_HOSTS=['sneakernews.com','www.sneakernews.com','nicekicks.com','www.nicekicks.com'];
function trustedArticle(url=''){try{return TRUSTED_ARTICLE_HOSTS.includes(new URL(url).hostname.toLowerCase())}catch{return false}}
function metaImage(html=''){const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["']/i];for(const re of patterns){const m=html.match(re);if(m?.[1])return m[1].replace(/&amp;/g,'&')}return ''}
async function articleImage(url){if(!trustedArticle(url))return '';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);const r=await fetch(url,{next:{revalidate:7200},redirect:'follow',signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0','Accept':'text/html,application/xhtml+xml'}});clearTimeout(timer);if(!r.ok)return '';const html=await r.text();const found=metaImage(html);if(!found)return '';return new URL(found,url).toString()}catch{return ''}}
async function hydrateImages(rows){const missing=rows.map((row,index)=>({row,index})).filter(x=>!x.row.image&&trustedArticle(x.row.url)).slice(0,10);if(!missing.length)return rows;const found=await Promise.all(missing.map(x=>articleImage(x.row.url)));const copy=rows.map(x=>({...x}));missing.forEach((x,i)=>{if(found[i])copy[x.index].image=found[i]});return copy}
const fallback=[
{source:'Sneaker News',title:'Kith And On Running Branch Into Lifestyle With The K-Tech 3',url:'https://sneakernews.com/2026/09/16/kith-on-running-k-tech-fall-2026/',date:'Wed, 16 Sep 2026 16:30:00 GMT',summary:'Kith and On expand their K-Tech partnership with the new lifestyle-focused K-Tech 3 plus fresh K-Tech 1 and 2 colorways, releasing September 18.',image:''},
{source:'Sneaker News',title:'Air Jordan 9 “Charcoal” Returning In 2027',url:'https://sneakernews.com/2026/09/16/air-jordan-9-charcoal-2027/',date:'Wed, 16 Sep 2026 16:15:00 GMT',summary:'Sneaker News reports the original Air Jordan 9 “Charcoal” is returning in true-to-OG form for Fall 2027.',image:''},
{source:'Sneaker News',title:'Nike Kobe 5 Protro “What The Rick” Releasing In 2027',url:'https://sneakernews.com/2026/09/16/jalen-brunson-nike-kobe-5-protro-what-the-rick-ja7364-800/',date:'Wed, 16 Sep 2026 16:00:00 GMT',summary:'Jalen Brunson’s Nike Kobe 5 Protro “What The Rick,” a tribute to his father Rick Brunson, is reportedly headed for a public Summer 2027 release.',image:''},
{source:'Sneaker News',title:'Howard University Has Another Air Jordan 1 Low OG Release On The Way',url:'https://sneakernews.com/2026/09/16/air-jordan-1-retro-low-og-howard-bison-ix8478-410/',date:'Wed, 16 Sep 2026 15:45:00 GMT',summary:'Jordan Brand is preparing another Howard University-inspired Air Jordan 1 Low OG, continuing its recent HBCU-focused footwear storytelling.',image:''},
{source:'Sneaker News',title:'Rosé And PUMA Expand Their Speedcat Catalog On October 8th',url:'https://sneakernews.com/2026/09/15/rose-puma-speedcat-og-fall-2026/',date:'Tue, 15 Sep 2026 23:15:00 GMT',summary:'Rosé and PUMA expand their Speedcat partnership with new Fall 2026 styles scheduled to release October 8.',image:''},
{source:'Sneaker News',title:'The adidas Gazelle SPZL Returns In Black And White',url:'https://sneakernews.com/2026/09/15/adidas-gazelle-spzl-fc-hp4248/',date:'Tue, 15 Sep 2026 23:05:00 GMT',summary:'Sneaker News spotlights the return of the adidas Gazelle SPZL FC in a versatile black-and-white terrace-inspired colorway.',image:''},
{source:'Sneaker News',title:'The Resurgent Nike Zoom Streak 3 Arrives With Tiger Stripes',url:'https://sneakernews.com/2026/09/15/nike-zoom-streak-3-total-orange-black-white-iq8012-800/',date:'Tue, 15 Sep 2026 22:55:00 GMT',summary:'Nike continues the Zoom Streak 3 revival with a Total Orange, black and white edition featuring bold tiger-stripe detailing.',image:''},
{source:'Sneaker News',title:'Official Images Of The Nike AlphaFly 4',url:'https://sneakernews.com/2026/09/15/nike-alphafly-4-iu4686-002/',date:'Tue, 15 Sep 2026 22:45:00 GMT',summary:'Official images reveal the next-generation Nike AlphaFly 4 as Nike advances its flagship carbon-plated super-shoe line.',image:''},
{source:'Sneaker News',title:'Official Images Of The Nike Caitlin 1 “Warning Code”',url:'https://sneakernews.com/2026/09/15/nike-caitlin-1-warning-code-ih7423-700/',date:'Tue, 15 Sep 2026 20:30:00 GMT',summary:'Official images reveal the Nike Caitlin 1 “Warning Code” in Yellow Zest and Racer Blue ahead of its Fall/Winter 2026 release at $140.',image:''},
{source:'Sneaker News',title:'adidas Made A Samba Climbing Shoe',url:'https://sneakernews.com/2026/09/15/adidas-samba-climbing-shoes/',date:'Tue, 15 Sep 2026 20:15:00 GMT',summary:'adidas transforms the Samba into a technical climbing shoe with Five Ten STEALTH rubber; the black-and-orange pair releases October 6 for $120.',image:''},
{source:'Sneaker News',title:'Supreme Is Bringing Back Diamond Plate Timberland Boots',url:'https://sneakernews.com/2026/09/15/supreme-timberland-diamond-plate-boots-fw26/',date:'Tue, 15 Sep 2026 20:00:00 GMT',summary:'Supreme and Timberland revive their Diamond Plate 6-inch Premium Waterproof Boot in black and wheat, releasing September 17.',image:''},
{source:'Sneaker News',title:'The Patta x Crocs EXP Clog Drops September 18th',url:'https://sneakernews.com/2026/09/08/patta-crocs-classic-clog-vibram/',date:'Tue, 15 Sep 2026 18:45:00 GMT',summary:'Sneaker News confirms Patta’s rugged Crocs EXP Clog collaboration drops September 18 in black and white colorways, alongside an exclusive Jibbitz pack.',image:''},
{source:'Sneaker News',title:'Bad Bunny Gets Low With The Upcoming adidas Badbo 1.1',url:'https://sneakernews.com/2026/09/03/adidas-badbo-1-1-chalk-white-grey-soft-pink-lc5466/',date:'Tue, 15 Sep 2026 18:30:00 GMT',summary:'Bad Bunny and adidas introduce the lower-cut Badbo 1.1 in Chalk White, Grey and Soft Pink, with the $120 release landing September 15.',image:''},
{source:'Sneaker News',title:'The Air Jordan 1 “Beyond The Spider-Verse” Will Be A Full Family Release',url:'https://sneakernews.com/2026/09/04/spider-man-air-jordan-1-beyond-the-spider-verse-ja1074-001/',date:'Tue, 15 Sep 2026 17:00:00 GMT',summary:'Sneaker News reports the Air Jordan 1 “Beyond The Spider-Verse” is now expected to release in full-family sizing in Summer 2027, timed around the film’s June premiere.',image:''},
{source:'Sneaker News',title:'adidas Tries “Rich Green” On The Snakeskin Samba',url:'https://sneakernews.com/2026/09/14/adidas-samba-snakeskin-rich-green-wonder-mauve-gold-metallic-kk2473/',date:'Tue, 15 Sep 2026 09:00:00 GMT',summary:'Sneaker News spotlights a new adidas Samba with Rich Green snakeskin overlays, Wonder Mauve accents and Gold Metallic branding as the animal-print trend continues.',image:''},
{source:'Sneaker News',title:'The Air Jordan 4014 “Ferrari” Releases On September 26th',url:'https://sneakernews.com/2025/12/16/air-jordan-4014-ferrari-ir2082-600/',date:'Tue, 15 Sep 2026 03:10:00 GMT',summary:'Sneaker News confirms the red Air Jordan 4014 “Ferrari” hybrid will release September 26, 2026 via SNKRS for $200.',image:''},
{source:'Sneaker News',title:'The Nike Kobe 3 Protro “Orca” Releases On September 26th',url:'https://sneakernews.com/2026/08/05/nike-kobe-3-protro-orca-iq5340-001/',date:'Tue, 15 Sep 2026 03:00:00 GMT',summary:'Official images have surfaced for the Nike Kobe 3 Protro “Orca,” now confirmed for a September 26, 2026 release at $210.',image:''},
{source:'Sneaker News',title:'Ronnie Fieg Walks Through 15 Years Of KITH Collabs In The Footwear Archive',url:'https://sneakernews.com/2026/09/14/kith-the-footwear-archive-book/',date:'Tue, 15 Sep 2026 01:15:00 GMT',summary:'KITH marks its 15th anniversary with The Footwear Archive, documenting 700 released pairs plus unreleased samples. The book launches September 30, with a Brooklyn exhibit running September 25–27.',image:''},
{source:'Sneaker News',title:'Travis Scott x Air Jordan 1 Low Reportedly Releasing In A Chicago-Like Colorway',url:'https://sneakernews.com/2026/09/14/travis-scott-air-jordan-1-low-og-red-chicago/',date:'Mon, 14 Sep 2026 23:00:00 GMT',summary:'A new Travis Scott x Air Jordan 1 Low OG is reportedly planned for 2027 with dark red, white and black Chicago-like color blocking and the signature reverse Swoosh.',image:''},
{source:'Nice Kicks',title:'Nike Air Bakin SP “OG” Returns September 29',url:'https://www.nicekicks.com/nike-air-bakin-sp-og-iq5365-600/',date:'Mon, 14 Sep 2026 20:30:00 GMT',summary:'The cult-favorite Nike Air Bakin returns in its original black, red and yellow palette on September 29, 2026, priced at $170.',image:''},
{source:'Sneaker News',title:'Official Images Of The Air Jordan 5 “Sunset”',url:'https://sneakernews.com/2026/09/14/air-jordan-5-sunset-iv5678-102-release-date/',date:'Mon, 14 Sep 2026 20:00:00 GMT',summary:'Official images confirm the first retro of the women’s Air Jordan 5 “Sunset,” returning September 25, 2026 for $205.',image:''},
{source:'Sneaker News',title:'Reebok Enters Super-Shoe Territory With First-Ever Carbon Plated Running Shoe',url:'https://sneakernews.com/2026/09/14/reebok-speedshifter-running-shoe-carbon-fiber-plate/',date:'Mon, 14 Sep 2026 19:30:00 GMT',summary:'Reebok unveils the SpeedShifter, its first performance running shoe built with a full-length carbon plate, marking a major step in its running revival.',image:''},
{source:'Sneaker News',title:'Five Things You Won’t Find In The Nike Caitlin 1 Press Release',url:'https://sneakernews.com/2026/09/14/nike-caitlin-1/',date:'Mon, 14 Sep 2026 18:30:00 GMT',summary:'Sneaker News takes a deeper look at Caitlin Clark’s first Nike signature shoe ahead of its October 1 global launch.',image:''},
{source:'Sneaker News',title:'Air Jordan 1s Are Becoming Michael Jordan History Lessons',url:'https://sneakernews.com/2026/09/14/air-jordan-1-low-og-last-dance-in-the-garden-ir0088-001/',date:'Mon, 14 Sep 2026 15:00:00 GMT',summary:'The Air Jordan 1 Low OG “Last Dance At The Garden” commemorates Michael Jordan’s final game at Madison Square Garden as a Chicago Bull, continuing Jordan Brand’s history-driven storytelling.',image:''},
{source:'Sneaker News',title:'Nike Unleashes The “Beast” On This Kids’ Air Force 1',url:'https://sneakernews.com/2026/09/13/nike-air-force-1-easyon-the-beast-iq2292-001/',date:'Sun, 13 Sep 2026 23:30:00 GMT',summary:'Nike gives the kids’ Air Force 1 EasyOn a wild “Beast” treatment ahead of its September 20 retail release.',image:''},
{source:'Sneaker News',title:'The Jordan Spiz’ike Low Softens Up In “Swan”',url:'https://sneakernews.com/2026/09/13/jordan-spizike-low-swan-light-smoke-grey-purple-smoke-ir1836-105/',date:'Sun, 13 Sep 2026 22:30:00 GMT',summary:'Jordan Brand gives the women’s Spiz’ike Low a pastel Swan, violet and grey elephant-print treatment for Fall/Winter 2026, priced at $165.',image:''},
{source:'Sneaker News',title:'This Nike Air Force 1 Pack Reminds You To Be Mindful',url:'https://sneakernews.com/2026/09/13/nike-air-force-1-low-mindfulness-pack/',date:'Sun, 13 Sep 2026 21:30:00 GMT',summary:'Nike prepares a women’s Air Force 1 Low pack with hidden mindfulness messaging and two distinct colorways for Fall/Winter 2026.',image:''},
{source:'Sneaker News',title:'Jordan Brand Turns To Luxury Goods With The Air Jordan 1 Low “Bouclé”',url:'https://sneakernews.com/2026/09/13/air-jordan-1-low-boucle-iz6154-121/',date:'Sun, 13 Sep 2026 20:00:00 GMT',summary:'Jordan Brand gives the women’s Air Jordan 1 Low a luxury-textured Bouclé treatment for Fall/Winter 2026, priced at $125.',image:''},
{source:'Sneaker News',title:'Jordan 9 “Space Jam,” adidas AE3, And This Week’s Best Releases',url:'https://sneakernews.com/2026/09/13/sneaker-releases-september-13-september-19-2026/',date:'Sun, 13 Sep 2026 17:00:00 GMT',summary:'Sneaker News rounds up the key September 13–19 drops, led by the Air Jordan 9 “Space Jam,” adidas AE3, MOWALOLA x Jordan, adidas Jellyfish and Nike Kobe 8 “Mambacurial.”',image:''},
{source:'Sneaker News',title:'“Pink Foam” Contrast Stitching Distinguishes This Nike Zoom Vomero 5',url:'https://sneakernews.com/2026/09/12/nike-zoom-vomero-5-black-pink-foam-dusty-pink-fj2028-005/',date:'Sat, 12 Sep 2026 23:30:00 GMT',summary:'Sneaker News spotlights a new Nike Zoom Vomero 5 combining a black base with restrained Pink Foam and Dusty Pink contrast details.',image:''},
{source:'Sneaker News',title:'Where To Buy The Air Jordan 12 “Bucks”',url:'https://sneakernews.com/2026/09/11/air-jordan-12-bucks-store-list/',date:'Fri, 11 Sep 2026 21:00:00 GMT',summary:'The Air Jordan 12 “Bucks,” inspired by Ray Allen’s celebrated PE, releases September 12 in full-family sizing with adult pairs priced at $215.',image:''},
{source:'Nice Kicks',title:'adidas Anthony Edwards 3 “Cold Blooded” Releases September 18',url:'https://www.nicekicks.com/adidas-anthony-edwards-3-cold-blooded-kh8537-2026/',date:'Fri, 11 Sep 2026 19:00:00 GMT',summary:'Anthony Edwards enters the next chapter of his signature line with the adidas AE 3 “Cold Blooded,” releasing September 18 for $130.',image:''},
{source:'Nice Kicks',title:'MOWALOLA x Air Jordan 14 SP “Burnt Red” Drops September 18',url:'https://www.nicekicks.com/mowalola-air-jordan-14-sp-burnt-red-iq5708-001/',date:'Fri, 11 Sep 2026 18:30:00 GMT',summary:'Mowalola brings a distressed Burnt Red finish and Metallic Gold accents to the Ferrari-inspired Air Jordan 14, releasing September 18 for $255.',image:''},
{source:'Nice Kicks',title:'Anthony Edwards x adidas Superstar II “Bliss Blue” Releases September 18',url:'https://www.nicekicks.com/anthony-edwards-adidas-superstar-ii-bliss-blue-la7828/',date:'Fri, 11 Sep 2026 18:00:00 GMT',summary:'Anthony Edwards adds a Clear Blue, Tech Grey Metallic and Cloud White Superstar II to his adidas lineup, releasing September 18 for $110.',image:''},
{source:'Sneaker News',title:'Aminé Reveals New Balance 992 “Outdoor School” Collaboration',url:'https://sneakernews.com/2026/09/10/amine-new-balance-992/',date:'Thu, 10 Sep 2026 20:00:00 GMT',summary:'Aminé reveals his first New Balance Made in USA collaboration, transforming the 992 into the outdoors-inspired “Outdoor School” for Fall 2026.',image:''},
{source:'Sneaker News',title:'COMME des GARÇONS x Air Jordan 11 Is Available Now',url:'https://sneakernews.com/2026/09/03/comme-des-garcons-air-jordan-11-release-date/',date:'Thu, 10 Sep 2026 18:00:00 GMT',summary:'Sneaker News updates availability for the premium COMME des GARÇONS Homme Plus x Air Jordan 11 in black and white after its September 5 launch.',image:''}
];
export async function GET(){try{const feeds=[['Sneaker News','https://sneakernews.com/feed/'],['Nice Kicks','https://www.nicekicks.com/feed/']];const rows=[...fallback];for(const[source,url]of feeds){try{const r=await fetch(url,{next:{revalidate:7200},headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0'}});if(r.ok)rows.push(...parse(await r.text(),source))}catch{}}const seen=new Set();let news=rows.filter(x=>{if(seen.has(x.url))return false;seen.add(x.url);return true}).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0)).slice(0,18);news=await hydrateImages(news);return Response.json({news,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}catch{const news=await hydrateImages(fallback);return Response.json({news,updatedAt:new Date().toISOString()},{status:200,headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}}