function text(s=''){return s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&rsquo;/g,'’').replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/\s+/g,' ').trim()}
function tag(item,name){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?text(m[1]):''}
function image(item){let m=item.match(/<media:content[^>]+url=["']([^"']+)/i)||item.match(/<media:thumbnail[^>]+url=["']([^"']+)/i)||item.match(/<enclosure[^>]+url=["']([^"']+)/i)||item.match(/<img[^>]+src=["']([^"']+)/i);return m?m[1]:''}
function parse(xml,source){return (xml.match(/<item[\s\S]*?<\/item>/gi)||[]).slice(0,12).map(i=>({source,title:tag(i,'title'),url:tag(i,'link'),date:tag(i,'pubDate'),summary:tag(i,'description').slice(0,220),image:image(i)})).filter(x=>x.title&&x.url)}
const TRUSTED_ARTICLE_HOSTS=['sneakernews.com','www.sneakernews.com','nicekicks.com','www.nicekicks.com'];
function trustedArticle(url=''){try{return TRUSTED_ARTICLE_HOSTS.includes(new URL(url).hostname.toLowerCase())}catch{return false}}
function metaImage(html=''){const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["']/i];for(const re of patterns){const m=html.match(re);if(m?.[1])return m[1].replace(/&amp;/g,'&')}return ''}
async function articleImage(url){if(!trustedArticle(url))return '';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);const r=await fetch(url,{next:{revalidate:7200},redirect:'follow',signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0','Accept':'text/html,application/xhtml+xml'}});clearTimeout(timer);if(!r.ok)return '';const html=await r.text();const found=metaImage(html);if(!found)return '';return new URL(found,url).toString()}catch{return ''}}
async function hydrateImages(rows){const missing=rows.map((row,index)=>({row,index})).filter(x=>!x.row.image&&trustedArticle(x.row.url)).slice(0,10);if(!missing.length)return rows;const found=await Promise.all(missing.map(x=>articleImage(x.row.url)));const copy=rows.map(x=>({...x}));missing.forEach((x,i)=>{if(found[i])copy[x.index].image=found[i]});return copy}
const fallback=[
{source:'Sneaker News',title:'“Pink Foam” Contrast Stitching Distinguishes This Nike Zoom Vomero 5',url:'https://sneakernews.com/2026/09/12/nike-zoom-vomero-5-black-pink-foam-dusty-pink-fj2028-005/',date:'Sat, 12 Sep 2026 23:30:00 GMT',summary:'Sneaker News spotlights a new Nike Zoom Vomero 5 combining a black base with restrained Pink Foam and Dusty Pink contrast details.',image:''},
{source:'Sneaker News',title:'Where To Buy The Air Jordan 12 “Bucks”',url:'https://sneakernews.com/2026/09/11/air-jordan-12-bucks-store-list/',date:'Fri, 11 Sep 2026 21:00:00 GMT',summary:'The Air Jordan 12 “Bucks,” inspired by Ray Allen’s celebrated PE, releases September 12 in full-family sizing with adult pairs priced at $215.',image:''},
{source:'Nice Kicks',title:'MOWALOLA x Air Jordan 14 SP “Burnt Red” Drops September 18',url:'https://www.nicekicks.com/mowalola-air-jordan-14-sp-burnt-red-iq5708-001/',date:'Fri, 11 Sep 2026 18:30:00 GMT',summary:'Mowalola brings a distressed Burnt Red finish and Metallic Gold accents to the Ferrari-inspired Air Jordan 14, releasing September 18 for $255.',image:''},
{source:'Nice Kicks',title:'Anthony Edwards x adidas Superstar II “Bliss Blue” Releases September 18',url:'https://www.nicekicks.com/anthony-edwards-adidas-superstar-ii-bliss-blue-la7828/',date:'Fri, 11 Sep 2026 18:00:00 GMT',summary:'Anthony Edwards adds a Clear Blue, Tech Grey Metallic and Cloud White Superstar II to his adidas lineup, releasing September 18 for $110.',image:''},
{source:'Sneaker News',title:'Aminé Reveals New Balance 992 “Outdoor School” Collaboration',url:'https://sneakernews.com/2026/09/10/amine-new-balance-992/',date:'Thu, 10 Sep 2026 20:00:00 GMT',summary:'Aminé reveals his first New Balance Made in USA collaboration, transforming the 992 into the outdoors-inspired “Outdoor School” for Fall 2026.',image:''},
{source:'Sneaker News',title:'COMME des GARÇONS x Air Jordan 11 Is Available Now',url:'https://sneakernews.com/2026/09/03/comme-des-garcons-air-jordan-11-release-date/',date:'Thu, 10 Sep 2026 18:00:00 GMT',summary:'Sneaker News updates availability for the premium COMME des GARÇONS Homme Plus x Air Jordan 11 in black and white after its September 5 launch.',image:''},
{source:'Nice Kicks',title:'Nike Air Max 95 Big Bubble OG “Reverse Greedy”',url:'https://www.nicekicks.com/nike-air-max-95-big-bubble-og-reverse-greedy-im2211-001/',date:'Mon, 07 Sep 2026 16:00:00 GMT',summary:'Nike flips the celebrated Greedy theme for the Air Max 95 Big Bubble OG “Reverse Greedy,” released September 8 for $200.',image:''},
{source:'Nice Kicks',title:'Wagyu x Nike Air Max 90 “Black”',url:'https://www.nicekicks.com/wagyu-nike-air-max-90-black-ir1979-010/',date:'Wed, 02 Sep 2026 18:00:00 GMT',summary:'New York label Wagyu dresses the Air Max 90 in black suede and leather with gold accents and custom cow-head branding for a September 2026 release.',image:''},
{source:'Nice Kicks',title:'One Piece x Nike Air Max Plus SP “Gomu Gomu no Mi”',url:'https://www.nicekicks.com/one-piece-nike-air-max-plus-sp-gomu-gomu-no-mi-ir0968-500/',date:'Wed, 02 Sep 2026 17:00:00 GMT',summary:'Nike channels Luffy’s Gomu Gomu no Mi into a special Air Max Plus, part of the One Piece collaboration launching globally September 25 for $210.',image:''},
{source:'Sneaker News',title:'APB x Air Jordan 11 Low Releases September 18',url:'https://sneakernews.com/2026/08/31/apb-air-jordan-11-low-iu8266-400-release-date/',date:'Mon, 31 Aug 2026 18:00:00 GMT',summary:'APB brings its perspective to the Air Jordan 11 Low in a new collaboration scheduled to release September 18 for $200.',image:''},
{source:'Sneaker News',title:'Fat Joe’s Terror Squad x Nike Air Force 1 Is Available Now',url:'https://sneakernews.com/2026/08/26/fat-joe-terror-squad-nike-air-force-1-university-red-ii4391-100/',date:'Wed, 09 Sep 2026 16:00:00 GMT',summary:'Fat Joe’s Terror Squad Air Force 1 “University Red” returns through SNKRS and select retailers, reviving a Bronx-rooted sneaker story for $150.',image:''},
{source:'Nice Kicks',title:'Air Jordan 9 OG “Space Jam” Returns for the Film’s 30th Anniversary',url:'https://www.nicekicks.com/air-jordan-9-og-space-jam-ix6179-100-drop/',date:'Sat, 05 Sep 2026 23:00:00 GMT',summary:'The Air Jordan 9 OG “Space Jam” returns September 19 for the film’s 30th anniversary, with full-family sizing and an adult retail price of $215.',image:''}
];
export async function GET(){try{const feeds=[['Sneaker News','https://sneakernews.com/feed/'],['Nice Kicks','https://www.nicekicks.com/feed/']];const rows=[...fallback];for(const[source,url]of feeds){try{const r=await fetch(url,{next:{revalidate:7200},headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0'}});if(r.ok)rows.push(...parse(await r.text(),source))}catch{}}const seen=new Set();let news=rows.filter(x=>{if(seen.has(x.url))return false;seen.add(x.url);return true}).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0)).slice(0,18);news=await hydrateImages(news);return Response.json({news,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}catch{const news=await hydrateImages(fallback);return Response.json({news,updatedAt:new Date().toISOString()},{status:200,headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}}