function text(s=''){return s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&rsquo;/g,'’').replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/\s+/g,' ').trim()}
function tag(item,name){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?text(m[1]):''}
function image(item){let m=item.match(/<media:content[^>]+url=["']([^"']+)/i)||item.match(/<media:thumbnail[^>]+url=["']([^"']+)/i)||item.match(/<enclosure[^>]+url=["']([^"']+)/i)||item.match(/<img[^>]+src=["']([^"']+)/i);return m?m[1]:''}
function parse(xml,source){return (xml.match(/<item[\s\S]*?<\/item>/gi)||[]).slice(0,12).map(i=>({source,title:tag(i,'title'),url:tag(i,'link'),date:tag(i,'pubDate'),summary:tag(i,'description').slice(0,220),image:image(i)})).filter(x=>x.title&&x.url)}
const TRUSTED_ARTICLE_HOSTS=['sneakernews.com','www.sneakernews.com','nicekicks.com','www.nicekicks.com'];
function trustedArticle(url=''){try{return TRUSTED_ARTICLE_HOSTS.includes(new URL(url).hostname.toLowerCase())}catch{return false}}
function metaImage(html=''){const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["']/i];for(const re of patterns){const m=html.match(re);if(m?.[1])return m[1].replace(/&amp;/g,'&')}return ''}
async function articleImage(url){if(!trustedArticle(url))return '';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);const r=await fetch(url,{next:{revalidate:7200},redirect:'follow',signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0','Accept':'text/html,application/xhtml+xml'}});clearTimeout(timer);if(!r.ok)return '';const html=await r.text();const found=metaImage(html);if(!found)return '';return new URL(found,url).toString()}catch{return ''}}
async function hydrateImages(rows){const missing=rows.map((row,index)=>({row,index})).filter(x=>!x.row.image&&trustedArticle(x.row.url)).slice(0,10);if(!missing.length)return rows;const found=await Promise.all(missing.map(x=>articleImage(x.row.url)));const copy=rows.map(x=>({...x}));missing.forEach((x,i)=>{if(found[i])copy[x.index].image=found[i]});return copy}
const fallback=[
{source:'Sneaker News',title:'The New Balance 990v4 “Monarch Burgundy” Releases On September 24th',url:'https://sneakernews.com/2026/09/17/new-balance-990v4-made-in-usa-monarch-burgundy-pumpernickle-u990br4/',date:'Thu, 17 Sep 2026 22:00:00 GMT',summary:'New Balance adds a rich Monarch Burgundy and Pumpernickel 990v4 to its Made in USA Fall/Winter 2026 slate, releasing September 24.',image:''},
{source:'Sneaker News',title:'Bad Bunny’s adidas Badbo 1.0 “Puerto Rican Night” Releases September 26th',url:'https://sneakernews.com/2026/09/17/bad-bunny-adidas-badbo-1-0-puerto-rico-night-lb5996/',date:'Thu, 17 Sep 2026 17:10:00 GMT',summary:'Bad Bunny’s adidas Badbo 1.0 “Puerto Rican Night” is set to release September 26 for $160, continuing the Puerto Rico-inspired signature series.',image:''},
{source:'Sneaker News',title:'Tom Sachs’ Nike General Purpose Shoe Returns On September 30th',url:'https://sneakernews.com/2026/09/17/nike-tom-sachs-general-purpose-shoe-black-team-royal-fz1363-002/',date:'Thu, 17 Sep 2026 16:55:00 GMT',summary:'Tom Sachs’ Nike General Purpose Shoe returns in Black, White and Team Royal, with a September 30 European release confirmed.',image:''},
{source:'Sneaker News',title:'First Look At The Nike Kobe 8 Protro “Easter”',url:'https://sneakernews.com/2026/09/17/nike-kobe-8-protro-easter-ja7323-300-release-date/',date:'Thu, 17 Sep 2026 15:00:00 GMT',summary:'The Nike Kobe 8 Protro “Easter” is returning for Spring 2027 in its familiar seasonal colorway with updated performance tooling.',image:''},
{source:'Sneaker News',title:'The Nike Zoom Huarache 2K4 Takes On “UCLA” Colors',url:'https://sneakernews.com/2026/09/17/nike-zoom-huarache-2k4-ucla-iv3782-101/',date:'Thu, 17 Sep 2026 14:45:00 GMT',summary:'Nike dresses the returning Zoom Huarache 2K4 in a UCLA-inspired palette for Fall/Winter 2026.',image:''},
{source:'Sneaker News',title:'Song For The Mute’s adidas FW26 Collection Drops September 18th',url:'https://sneakernews.com/2026/09/16/song-for-the-mute-adidas-samba-evo-pro-sl/',date:'Wed, 16 Sep 2026 23:15:00 GMT',summary:'Song For The Mute and adidas return with six Fall/Winter 2026 styles spanning the Samba and SL 72 Pro, releasing September 18.',image:''},
{source:'Sneaker News',title:'Where To Buy The One Piece x Nike Air Max Plus “Ope Ope”',url:'https://sneakernews.com/2026/09/16/one-piece-nike-air-max-plus-ope-ope-iw1283-600/',date:'Wed, 16 Sep 2026 22:55:00 GMT',summary:'The One Piece x Nike Air Max Plus “Ope Ope” releases September 19 in the United States and Europe for $210.',image:''},
{source:'Sneaker News',title:'Caitlin Clark Debuts The Nike Caitlin 1 “3x Black”',url:'https://sneakernews.com/2026/09/16/nike-caitlin-1-3x-black-ih7423-001/',date:'Wed, 16 Sep 2026 18:55:00 GMT',summary:'Caitlin Clark previews the all-black Nike Caitlin 1 “3x Black,” scheduled for January 5, 2027 at $140.',image:''},
{source:'Sneaker News',title:'The Nike Kobe 3 Low Lets Loose A Mismatched Kids’ Pair On September 19th',url:'https://sneakernews.com/2026/08/19/nike-kobe-3-low-protro-mismatch-blue-green-iz7934-900/',date:'Wed, 16 Sep 2026 18:45:00 GMT',summary:'The kids-only Nike Kobe 3 Low Protro “Mismatch” is now confirmed for September 19, 2026 at $122.',image:''},
{source:'Sneaker News',title:'New Balance Debuts The 990v7 With A Tiny Teaser On A Billboard',url:'https://sneakernews.com/2026/09/16/new-balance-990v7/',date:'Wed, 16 Sep 2026 18:30:00 GMT',summary:'New Balance has begun teasing the long-awaited 990v7 with a first look and New York billboard campaign.',image:''},
{source:'Sneaker News',title:'Kith And On Running Branch Into Lifestyle With The K-Tech 3',url:'https://sneakernews.com/2026/09/16/kith-on-running-k-tech-fall-2026/',date:'Wed, 16 Sep 2026 16:30:00 GMT',summary:'Kith and On expand their K-Tech partnership with the lifestyle-focused K-Tech 3 plus fresh K-Tech 1 and 2 colorways, releasing September 18.',image:''},
{source:'Sneaker News',title:'Air Jordan 9 “Charcoal” Returning In 2027',url:'https://sneakernews.com/2026/09/16/air-jordan-9-charcoal-2027/',date:'Wed, 16 Sep 2026 16:15:00 GMT',summary:'The original Air Jordan 9 “Charcoal” is reportedly returning in true-to-OG form for Fall 2027.',image:''},
{source:'Sneaker News',title:'Nike Kobe 5 Protro “What The Rick” Releasing In 2027',url:'https://sneakernews.com/2026/09/16/jalen-brunson-nike-kobe-5-protro-what-the-rick-ja7364-800/',date:'Wed, 16 Sep 2026 16:00:00 GMT',summary:'Jalen Brunson’s Nike Kobe 5 Protro “What The Rick” is reportedly headed for a public Summer 2027 release.',image:''},
{source:'Sneaker News',title:'Howard University Has Another Air Jordan 1 Low OG Release On The Way',url:'https://sneakernews.com/2026/09/16/air-jordan-1-retro-low-og-howard-bison-ix8478-410/',date:'Wed, 16 Sep 2026 15:45:00 GMT',summary:'Jordan Brand is preparing another Howard University-inspired Air Jordan 1 Low OG.',image:''},
{source:'Sneaker News',title:'Rosé And PUMA Expand Their Speedcat Catalog On October 8th',url:'https://sneakernews.com/2026/09/15/rose-puma-speedcat-og-fall-2026/',date:'Tue, 15 Sep 2026 23:15:00 GMT',summary:'Rosé and PUMA expand their Speedcat partnership with new Fall 2026 styles scheduled to release October 8.',image:''},
{source:'Sneaker News',title:'Official Images Of The Nike AlphaFly 4',url:'https://sneakernews.com/2026/09/15/nike-alphafly-4-iu4686-002/',date:'Tue, 15 Sep 2026 22:45:00 GMT',summary:'Official images reveal the next-generation Nike AlphaFly 4.',image:''},
{source:'Sneaker News',title:'Official Images Of The Nike Caitlin 1 “Warning Code”',url:'https://sneakernews.com/2026/09/15/nike-caitlin-1-warning-code-ih7423-700/',date:'Tue, 15 Sep 2026 20:30:00 GMT',summary:'Official images reveal the Nike Caitlin 1 “Warning Code” ahead of its October 1 release at $140.',image:''},
{source:'Nice Kicks',title:'Nike Air Bakin SP “OG” Returns September 29',url:'https://www.nicekicks.com/nike-air-bakin-sp-og-iq5365-600/',date:'Mon, 14 Sep 2026 20:30:00 GMT',summary:'The Nike Air Bakin returns in its original black, red and yellow palette on September 29, 2026 for $170.',image:''}
];
export async function GET(){try{const feeds=[['Sneaker News','https://sneakernews.com/feed/'],['Nice Kicks','https://www.nicekicks.com/feed/']];const rows=[...fallback];for(const[source,url]of feeds){try{const r=await fetch(url,{next:{revalidate:7200},headers:{'User-Agent':'Mozilla/5.0 DiceyShoes/1.0'}});if(r.ok)rows.push(...parse(await r.text(),source))}catch{}}const seen=new Set();let news=rows.filter(x=>{if(seen.has(x.url))return false;seen.add(x.url);return true}).sort((a,b)=>Date.parse(b.date||0)-Date.parse(a.date||0)).slice(0,18);news=await hydrateImages(news);return Response.json({news,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}catch{const news=await hydrateImages(fallback);return Response.json({news,updatedAt:new Date().toISOString()},{status:200,headers:{'Cache-Control':'public, s-maxage=7200, stale-while-revalidate=7200'}})}}